---
- name: Prepare servers for deployment
  hosts: all
  become: true
  roles:
    - geerlingguy.pip

  tasks:
    - name: Install Docker Engine
      ansible.builtin.apt:
        name: docker.io
        state: present
        update_cache: yes
    - name: Install Docker Python library
      ansible.builtin.command:
        cmd: "pip3 install docker"
        creates: /usr/local/bin/docker
